function HompageSliderComponent() {
    return (
        <div className="homepage-slider">
            <div id="rev_slider_1_1_wrapper" className="rev_slider_wrapper fullwidthbanner-container" data-alias="home-01" data-source="gallery" style={{ "margin": "0px auto", "background": "transparent", "padding": "0px", "marginTop": "0px", "marginBottom": "0px" }}>
                {/* START REVOLUTION SLIDER 5.4.7 fullwidth mode */}
                <div id="rev_slider_1_1" className="rev_slider fullwidthabanner" style={{ "display": "none" }} data-version="5.4.7">
                    <ul>
                        {/* SLIDE  */}
                        <li data-index="rs-1" data-transition="fade,random-premium" data-slotamount="default,default" data-hideafterloop={0} data-hideslideonmobile="off" data-easein="default,default" data-easeout="default,default" data-masterspeed="300,default" data-thumb="./src/assets/img/slider/home-01/100x50_m1-s1-1.jpg" data-rotate="0,0" data-saveperformance="off" data-title={"01"} data-param1 data-param2 data-param3 data-param4 data-param5 data-param6 data-param7 data-param8 data-param9 data-param10 data-description>
                            {/* MAIN IMAGE */}
                            <img src="./src/assets/img/slider/home-01/m1-s1-1.jpg" alt data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" data-bgparallax={2} className="rev-slidebg" data-no-retina />
                            {/* LAYERS */}
                            {/* LAYER NR. 1 */}
                            <div className="tp-caption     rev_group" id="slide-1-layer-1" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['0','0','0','0']" data-width="['919','919','712','445']" data-height="['489','489','459','390']" data-whitespace="nowrap" data-type="group" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:10,&quot;speed&quot;:300,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-margintop="[0,0,0,0]" data-marginright="[0,0,0,0]" data-marginbottom="[0,0,0,0]" data-marginleft="[0,0,0,0]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{ "zIndex": "5", "minWidth": "919px", "maxWidth": "489px", "whiteSpace": "nowrap", "font-size": "20px", "lineHeight": "22px", "fontWeight": "400", "color": "#ffffff", "letterSpacing": "0px" }}>
                                {/* LAYER NR. 2 */}
                                <div className="tp-caption   tp-resizeme" id="slide-1-layer-2" data-x="['left','left','left','left']" data-hoffset="['111','111','20','0']" data-y="['top','top','top','top']" data-voffset="['127','127','117','105']" data-fontsize="['50','50','40','30']" data-lineheight="['50','50','40','30']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="text" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:&quot;+390&quot;,&quot;speed&quot;:1500,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;x:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;&quot;,&quot;mask&quot;:&quot;x:0px;y:0px;s:inherit;e:inherit;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;auto:auto;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-margintop="[0,0,0,0]" data-marginright="[0,0,0,0]" data-marginbottom="[0,0,0,0]" data-marginleft="[0,0,0,0]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{ "zIndex": "6", "whiteSpace": "nowrap", "font-size": "50px", "lineHeight": "50px", "fontWeight": "400", "color": "#ffffff", "letterSpacing": "5px", "fontFamily": "Montserrat" }}>
                                    <strong>BIG </strong>SUMMER </div>
                                {/* LAYER NR. 3 */}
                                <div className="tp-caption   tp-resizeme" id="slide-1-layer-3" data-x="['center','center','center','center']" data-hoffset="['0','0','3','3']" data-y="['top','top','top','top']" data-voffset="['0','0','59','59']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="image" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:&quot;+710&quot;,&quot;speed&quot;:1500,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;x:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;&quot;,&quot;mask&quot;:&quot;x:0px;y:0px;s:inherit;e:inherit;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;auto:auto;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-margintop="[0,0,0,0]" data-marginright="[0,0,0,0]" data-marginbottom="[0,0,0,0]" data-marginleft="[0,0,0,0]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{ "zIndex": "7" }}>
                                    <img src="./src/assets/img/slider/home-01/m1-s1-1-1.png" alt data-ww="['692px','692px','452px','321px']" data-hh="['438px','438px','286px','203px']" data-no-retina /> </div>
                                {/* LAYER NR. 4 */}
                                <a className="tp-caption rev-btn " href="shop-sidebar.html" id="slide-1-layer-4" data-x="['center','center','center','center']" data-hoffset="['0','0','-1','0']" data-y="['top','top','top','top']" data-voffset="['398','398','371','279']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="button" data-responsive_offset="on" data-responsive="off" data-frames="[{&quot;delay&quot;:&quot;+1500&quot;,&quot;speed&quot;:2000,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;&quot;,&quot;mask&quot;:&quot;x:0px;y:[100%];s:inherit;e:inherit;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power2.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;auto:auto;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;frame&quot;:&quot;hover&quot;,&quot;speed&quot;:&quot;0&quot;,&quot;ease&quot;:&quot;Linear.easeNone&quot;,&quot;to&quot;:&quot;o:1;rX:0;rY:0;rZ:0;z:0;&quot;,&quot;style&quot;:&quot;c:rgb(255,255,255);bg:rgb(207,152,126);bs:solid;bw:0 0 0 0;&quot;}]" data-margintop="[0,0,0,0]" data-marginright="[0,0,0,0]" data-marginbottom="[0,0,0,0]" data-marginleft="[0,0,0,0]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[20,20,20,15]" data-paddingright="[45,45,45,35]" data-paddingbottom="[20,20,20,15]" data-paddingleft="[45,45,45,35]" style={{ "zIndex": "8", "whiteSpace": "nowrap", "font-size": "14px", "lineHeight": "20px", "fontWeight": "700", "color": "#ffffff", "fontFamily": "Montserrat", "backgroundColor": "rgb(40,40,40)", "borderColor": "rgba(0,0,0,1)", "outline": "none", "boxShadow": "none", "box-sizing": "border-box", "-moz-box-sizing": "border-box", "-webkit-box-sizing": "border-box", "cursor": "pointer" }}>Shop
                                    Now </a>
                            </div>
                        </li>
                        {/* SLIDE  */}
                        <li data-index="rs-2" data-transition="random-premium" data-slotamount="default" data-hideafterloop={0} data-hideslideonmobile="off" data-easein="default" data-easeout="default" data-masterspeed="default" data-thumb="./src/assets/img/slider/home-01/100x50_m1-s1-2.jpg" data-rotate={0} data-saveperformance="off" data-title={"02"} data-param1 data-param2 data-param3 data-param4 data-param5 data-param6 data-param7 data-param8 data-param9 data-param10 data-description>
                            {/* MAIN IMAGE */}
                            <img src="./src/assets/img/slider/home-01/m1-s1-2.jpg" alt data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" data-bgparallax={2} className="rev-slidebg" data-no-retina />
                            {/* LAYERS */}
                            {/* LAYER NR. 5 */}
                            <div className="tp-caption     rev_group" id="slide-2-layer-1" data-x="['right','right','center','center']" data-hoffset="['203','203','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['0','0','0','0']" data-width="['687','687','614','438']" data-height="['367','367','305','270']" data-whitespace="nowrap" data-type="group" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:10,&quot;speed&quot;:300,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-margintop="[0,0,0,0]" data-marginright="[0,0,0,0]" data-marginbottom="[0,0,0,0]" data-marginleft="[0,0,0,0]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{ "zIndex": "5", "minWidth": "687px", "maxWidth": "367px", "whiteSpace": "nowrap", "font-size": "20px", "lineHeight": "22px", "fontWeight": "400", "color": "#ffffff", "letterSpacing": "0px" }}>
                                {/* LAYER NR. 6 */}
                                <div className="tp-caption   tp-resizeme" id="slide-2-layer-2" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['top','top','top','top']" data-voffset="['0','0','0','0']" data-fontsize="['50','50','40','30']" data-lineheight="['70','70','50','40']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="text" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:&quot;+390&quot;,&quot;speed&quot;:1500,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;x:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;&quot;,&quot;mask&quot;:&quot;x:0px;y:0px;s:inherit;e:inherit;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;auto:auto;&quot;,&quot;mask&quot;:&quot;x:0;y:0;s:inherit;e:inherit;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-margintop="[0,0,0,0]" data-marginright="[0,0,0,0]" data-marginbottom="[0,0,0,0]" data-marginleft="[0,0,0,0]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{ "zIndex": "6", "whiteSpace": "nowrap", "font-size": "50px", "lineHeight": "70px", "fontWeight": "400", "color": "#ffffff", "letterSpacing": "0px", "fontFamily": "Playfair Display" }}>
                                    New Summer </div>
                                {/* LAYER NR. 7 */}
                                <div className="tp-caption   tp-resizeme" id="slide-2-layer-3" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['top','top','top','top']" data-voffset="['51','51','51','46']" data-fontsize="['165','165','120','100']" data-lineheight="['220','220','150','120']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="text" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:&quot;+790&quot;,&quot;speed&quot;:1500,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;x:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;&quot;,&quot;mask&quot;:&quot;x:0px;y:0px;s:inherit;e:inherit;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;auto:auto;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-margintop="[0,0,0,0]" data-marginright="[0,0,0,0]" data-marginbottom="[0,0,0,0]" data-marginleft="[0,0,0,0]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{ "zIndex": "7", "whiteSpace": "nowrap", "font-size": "165px", "lineHeight": "220px", "fontWeight": "400", "color": "#ffffff", "letterSpacing": "0px", "fontFamily": "Playfair Display" }}>
                                    Off 30% </div>
                                {/* LAYER NR. 8 */}
                                <a className="tp-caption rev-btn " href="shop-sidebar.html" id="slide-2-layer-4" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['top','top','top','top']" data-voffset="['299','299','235','202']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="button" data-responsive_offset="on" data-responsive="off" data-frames="[{&quot;delay&quot;:&quot;+1510&quot;,&quot;speed&quot;:1500,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;x:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;&quot;,&quot;mask&quot;:&quot;x:0px;y:0px;s:inherit;e:inherit;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;auto:auto;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;frame&quot;:&quot;hover&quot;,&quot;speed&quot;:&quot;300&quot;,&quot;ease&quot;:&quot;Linear.easeNone&quot;,&quot;to&quot;:&quot;o:1;rX:0;rY:0;rZ:0;z:0;&quot;,&quot;style&quot;:&quot;c:rgb(255,255,255);bg:rgb(40,40,40);bs:solid;bw:0 0 0 0;&quot;}]" data-margintop="[0,0,0,0]" data-marginright="[0,0,0,0]" data-marginbottom="[0,0,0,0]" data-marginleft="[0,0,0,0]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[15,15,15,12]" data-paddingright="[45,45,45,35]" data-paddingbottom="[15,15,15,12]" data-paddingleft="[45,45,45,35]" style={{ "zIndex": "8", "whiteSpace": "nowrap", "font-size": "14px", "lineHeight": "20px", "fontWeight": "400", "color": "#282828", "fontFamily": "Montserrat", "backgroundColor": "rgb(255,255,255)", "borderColor": "rgba(0,0,0,1)", "outline": "none", "boxShadow": "none", "box-sizing": "border-box", "-moz-box-sizing": "border-box", "-webkit-box-sizing": "border-box", "cursor": "pointer" }}>Shop
                                    now </a>
                            </div>
                        </li>
                        {/* SLIDE  */}
                        <li data-index="rs-3" data-transition="random-premium" data-slotamount="default" data-hideafterloop={0} data-hideslideonmobile="off" data-easein="default" data-easeout="default" data-masterspeed="default" data-thumb="./src/assets/img/slider/home-01/100x50_m1-s1-3.jpg" data-rotate={0} data-saveperformance="off" data-title={"03"} data-param1 data-param2 data-param3 data-param4 data-param5 data-param6 data-param7 data-param8 data-param9 data-param10 data-description>
                            {/* MAIN IMAGE */}
                            <img src="./src/assets/img/slider/home-01/m1-s1-3.jpg" alt data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" data-bgparallax={2} className="rev-slidebg" data-no-retina />
                            {/* LAYERS */}
                            {/* LAYER NR. 9 */}
                            <div className="tp-caption     rev_group" id="slide-3-layer-1" data-x="['left','left','center','center']" data-hoffset="['203','203','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['2','2','2','2']" data-width="['641','641','507','420']" data-height="['268','268','253','222']" data-whitespace="nowrap" data-type="group" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:10,&quot;speed&quot;:300,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-margintop="[0,0,0,0]" data-marginright="[0,0,0,0]" data-marginbottom="[0,0,0,0]" data-marginleft="[0,0,0,0]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{ "zIndex": "5", "minWidth": "641px", "maxWidth": "268px", "whiteSpace": "nowrap", "font-size": "20px", "lineHeight": "22px", "fontWeight": "400", "color": "#ffffff", "letterSpacing": "0px" }}>
                                {/* LAYER NR. 10 */}
                                <div className="tp-caption   tp-resizeme" id="slide-3-layer-2" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['top','top','top','top']" data-voffset="['0','0','0','0']" data-fontsize="['50','50','40','30']" data-lineheight="['50','50','50','40']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="text" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:&quot;+390&quot;,&quot;speed&quot;:1500,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;x:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;&quot;,&quot;mask&quot;:&quot;x:0px;y:0px;s:inherit;e:inherit;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;auto:auto;&quot;,&quot;mask&quot;:&quot;x:0;y:0;s:inherit;e:inherit;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-margintop="[0,0,0,0]" data-marginright="[0,0,0,0]" data-marginbottom="[0,0,0,0]" data-marginleft="[0,0,0,0]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{ "zIndex": "6", "whiteSpace": "nowrap", "font-size": "50px", "lineHeight": "50px", "fontWeight": "400", "color": "#ffffff", "letterSpacing": "0px", "fontFamily": "Playfair Display" }}>
                                    Men Blazer </div>
                                {/* LAYER NR. 11 */}
                                <div className="tp-caption   tp-resizeme" id="slide-3-layer-3" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['top','top','top','top']" data-voffset="['50','50','51','51']" data-fontsize="['120','120','100','80']" data-lineheight="['120','120','100','80']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="text" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:&quot;+790&quot;,&quot;speed&quot;:1500,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;x:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;&quot;,&quot;mask&quot;:&quot;x:0px;y:0px;s:inherit;e:inherit;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;auto:auto;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-margintop="[0,0,0,0]" data-marginright="[0,0,0,0]" data-marginbottom="[0,0,0,0]" data-marginleft="[0,0,0,0]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{ "zIndex": "7", "whiteSpace": "nowrap", "font-size": "120px", "lineHeight": "120px", "fontWeight": "400", "color": "#ffffff", "letterSpacing": "0px", "fontFamily": "Playfair Display" }}>
                                    New Now </div>
                                {/* LAYER NR. 12 */}
                                <a className="tp-caption rev-btn " href="shop-sidebar.html" id="slide-3-layer-4" data-x="['center','center','center','center']" data-hoffset="['0','0','0','2']" data-y="['top','top','top','top']" data-voffset="['200','200','188','164']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="button" data-responsive_offset="on" data-responsive="off" data-frames="[{&quot;delay&quot;:&quot;+1510&quot;,&quot;speed&quot;:1500,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;x:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;&quot;,&quot;mask&quot;:&quot;x:0px;y:0px;s:inherit;e:inherit;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;auto:auto;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;frame&quot;:&quot;hover&quot;,&quot;speed&quot;:&quot;300&quot;,&quot;ease&quot;:&quot;Linear.easeNone&quot;,&quot;to&quot;:&quot;o:1;rX:0;rY:0;rZ:0;z:0;&quot;,&quot;style&quot;:&quot;c:rgb(255,255,255);bg:rgb(40,40,40);bs:solid;bw:0 0 0 0;&quot;}]" data-margintop="[0,0,0,0]" data-marginright="[0,0,0,0]" data-marginbottom="[0,0,0,0]" data-marginleft="[0,0,0,0]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[15,15,15,12]" data-paddingright="[45,45,45,35]" data-paddingbottom="[15,15,15,12]" data-paddingleft="[45,45,45,35]" style={{ "zIndex": "8", "whiteSpace": "nowrap", "font-size": "14px", "lineHeight": "20px", "fontWeight": "400", "color": "#282828", "fontFamily": "Montserrat", "backgroundColor": "rgb(255,255,255)", "borderColor": "rgba(0,0,0,1)", "outline": "none", "boxShadow": "none", "box-sizing": "border-box", "-moz-box-sizing": "border-box", "-webkit-box-sizing": "border-box", "cursor": "pointer" }}>Shop
                                    now </a>
                            </div>
                        </li>
                    </ul>
                    <div className="tp-bannertimer tp-bottom" style={{ "visibility": "hidden !important" }} />
                </div>
            </div>{/* END REVOLUTION SLIDER */}
        </div>
    )
}

export default HompageSliderComponent